### ISSUE TITLE
Typescript Support?

### ISSUE THREAD

**Issue by niklasgrewe** [metonym/svg-to-svelte#4]
Hi, thank you for this handy library to generate my own icon library. It is possible for you to support typescript as well? I work only with Typescript, so it would be nice, if i have some type definitions for better developer experience and VS IntelliSense

**Comment by metonym** [comment]
Hi there – have a look at [svelvg](https://github.com/metonym/svelvg), which aims to be an improved version of svg-to-svelte.

svelvg will also generate a corresponding TypeScript definition for each Svelte component.

Here's a sample library that uses svelvg: https://github.com/metonym/svelte-codicons

Here's the output: https://unpkg.com/browse/svelte-codicons@0.5.0/

**Comment by niklasgrewe** [comment]
thank you that's exactly what i was looking for 👍
